name: gifire
version: 1.0.0+52
publish_to: none
description: start your project in the fastest way
environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  get: ^4.6.5 # for state management and context less stuff

  logger: ^1.4.0  # log events in clear way insted of (print)
  flutter_inappwebview: ^6.1.5
  curved_navigation_bar: ^1.0.6
  flutter_easyloading: ^3.0.3
  easy_localization: ^3.0.2
  url_launcher: ^6.3.1
  url_launcher_ios: ^6.3.1
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.3
  dartz: ^0.10.1


  change_app_package_name:
  loading_animation_widget: ^1.3.0
  flutter_zoom_drawer: ^2.3.1+1
  get_it:
  #flutter_screenutil:
  fluttertoast: ^8.2.4
  dio: ^5.2.1+1 # for api requests
  pretty_dio_logger: ^1.3.1 # for dio api logging and debugging

  shared_preferences: ^2.2.0 # shared preferences persistence key value store
  webview_flutter: ^4.3.0
  flutter_native_splash: ^2.4.3
  # rename_app: 1.0.0 # rename app
  connectivity_plus: ^6.1.1
  firebase_core: ^3.10.0
  firebase_remote_config: ^5.2.0
  firebase_database: ^11.3.0
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.0
  retry: ^3.1.2

  flutter:
    sdk: flutter
  tab_container: ^3.5.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  mockito:
  flutter_lints:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/images/splash.png
  android_12:
    color: "#ffffff"
    color_dark: "#000000"
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#000000"
    image: assets/images/android12.png
    image_dark: assets/images/android12.png

# dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/images/icons/ios.png"
  image_path_ios_dark_transparent: "assets/images/icons/ios18.png"
  android: true # can specify file name here e.g. "ic_launcher"
  adaptive_icon_foreground: "assets/images/icons/android12.png" # Set the foreground image (same or different from image_path)
  adaptive_icon_background: "#000000"
  ios: true 
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  desaturate_tinted_to_grayscale_ios: true
  background_color_ios: "#ffffff"



  assets:
      - assets/
      - assets/images/
      - assets/images/icons/
      - assets/vectors/
      - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/Cairo-Medium.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 900

flutter:
  uses-material-design: true


